languageCode = "en-us"
title = "Dane Lipscombe"
baseurl = "http://lipscombe.com.au/"
theme="material-design"
paginate = 9 # To specify a multiple of 3
#disqusShortname = "Your Disqus Name" # optional
#copyright = "© 2015 Copyright Text"

[params]
  description = "Coder and DevOp" # optional
  twitter = "danelips" # optional
#  gitlab = "Your Gitlab Name" # optional
  github = "dlip" # optional
  facebook = "dane.lipscombe" # optional
  gplus = "DaneLipscombe" # optional
  linkedin = "danelipscombe" # optional
#  headerCover = "images/headerCover.png" # optional
#  footerCover = "images/footerCover.png" # optional
#  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional

